refactored import_commands function
AlbertaSat/ex2_ground_station_website pull request #112
Opened 2022-08-14 07:05 UTC by gurbirsandha

all telecommands should now get added into database

2022-08-14 18:42 UTC, gurbirsandha commented
This should be good to go except for a couple of minor merge conflicts.

2022-08-15 00:51 UTC, jmmabanta requested changes
I really like the look of the new help screen for the commands! Just need to provide a blank default value to the `about_info` parameter in `add_telecommand()` so unit tests pass and a small change in the help menu about how args are formatted (which are now separated by a comma).

I also fixed the merge conflict so make sure you `git pull` first so you get these changes locally.

2022-08-15 00:51 UTC, jmmabanta commented on groundstation/backend_api/utils.py
> +def add_telecommand(command_name, num_arguments, is_dangerous, about_info):
```suggestion
def add_telecommand(command_name, num_arguments, is_dangerous, about_info=''):
```
Add a blank default about_info so unit tests pass

2022-08-15 00:51 UTC, jmmabanta commented on groundstation/static/js/components/Help.jsx
> +            Commands are formatted as "prefix.command_name(arg1 arg2 ...) "
```suggestion
            Commands are formatted as "prefix.command_name(arg1,arg2,arg3,...) "
```
The command format has changed where args are now separated by a comma

2022-08-15 02:24 UTC, jmmabanta approved these changes

2022-08-15 02:24 UTC, merged